
syntax = "proto3";
package mixnet;

service Mix {
  rpc NewRound(NewRoundRequest) returns (NewRoundResponse) {}
  rpc EndRound(EndRoundRequest) returns (EndRoundResponse) {}

  rpc AddMessages(stream AddMessagesRequest) returns (AddMessagesResponse) {}
  rpc GetMessages(GetMessagesRequest) returns (GetMessagesResponse) {}
  rpc StartRound(StartRoundRequest) returns (StartRoundResponse) {}

  rpc SubmitCiphertexts(stream SubmitCiphertextsRequest) returns (SubmitCiphertextsResponse) {}
  rpc VerifyProof(stream VerifyProofRequest) returns (VerifyProofResponse) {}
  rpc ConfirmVerification(ConfirmVerificationRequest) returns (ConfirmVerificationResponse) {}

  // inner ciphertext related
  rpc GetInnerKey(GetInnerKeyRequest) returns (GetInnerKeyResponse) {}
  rpc AddInnerCiphertexts(AddInnerCiphertextsRequest) returns (AddInnerCiphertextsResponse) {}
  rpc GetPrivateInnerKey(GetPrivateInnerKeyRequest) returns (GetPrivateInnerKeyResponse) {}
  rpc Finalize(FinalizeRequest) returns (FinalizeResponse) {}
}
