syntax = "proto3";
package mix;

service Mix {
    rpc Setup(SetupRequest) returns (SetupResponse) {}

    rpc Add(AddRequest) returns (AddResponse) {}

    // only coordinator calls this:
    rpc Get(GetRequest) returns (GetResponse) {}
    // rpc Start()
}

  // grpc context, prepares all circuits for following round.
  message SetupRequest {
    repeated bytes packets = 1;
  }

  message SetupResponse {
  }

  message AddRequest {
    repeated bytes packets = 1;
  }
  
  message AddResponse {
  }

  message GetRequest {
  }
  
  message GetResponse {
    repeated bytes messages = 1;
  }