syntax = "proto3";
package mix;

service Mix {
    rpc Setup(PacketRequest) returns (PacketResponse) {}

    rpc Add(PacketRequest) returns (PacketResponse) {}

    // only coordinator calls this:
    rpc Get(GetRequest) returns (GetResponse) {}
    // rpc Start()
}

  // grpc context, prepares all circuits for following round.
  // For round i, from: mix m in layer l or coordinator, for: mix n in layer l+1 OR for cordinator
  message PacketRequest {
    repeated bytes packets = 1;
    uint32 layer = 2;
  }

  message PacketResponse {
  }

  message GetRequest {
  }
  
  message GetResponse {
    repeated bytes messages = 1;
  }