syntax = "proto3";
package mix;

service Mix {
    rpc Add(AddRequest) returns (AddResponse) {}

    // only coordinator calls this:
    rpc Get(GetRequest) returns (stream GetResponse) {}
    // rpc Start()
}

// grpc context (for round i, from mix m in layer l, for mix n in layer l+1 OR for cordinator)
message AddRequest {
    repeated bytes packets = 1;
    uint32 layer = 2;
  }
  
  message AddResponse {
  }

  message GetRequest {
  }
  
  message GetResponse {
    repeated bytes messages = 1;
  }